name: Build and Deploy to Staging/Production

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write
  deployments: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Inject environment variables
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "docker_tag=latest" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "develop" ]]; then
            echo "docker_tag=staging" >> $GITHUB_ENV
          else
            echo "Unsupported branch for build"
            exit 1
          fi

      - name: Build and Push Docker Image
        run: |
          docker build --build-arg ENV_FILE=.env -t ${{ secrets.DOCKER_USERNAME }}/jozo-client:${{ env.docker_tag }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/jozo-client:${{ env.docker_tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Inject environment variables
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "env=production" >> $GITHUB_ENV
            echo "docker_tag=latest" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "develop" ]]; then
            echo "env=staging" >> $GITHUB_ENV
            echo "docker_tag=staging" >> $GITHUB_ENV
          else
            echo "Unsupported branch for deployment"
            exit 1
          fi

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/jozo-client:${{ env.docker_tag }}
            docker stop jozo-client || true
            docker rm jozo-client || true
            docker run -d \
              --name jozo-client \
              -p 3000:3000 \
              ${{ secrets.DOCKER_USERNAME }}/jozo-client:${{ env.docker_tag }}
