name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ezinn-client:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ezinn-client:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/ezinn-client:latest
            docker stop ezinn-client || true
            docker rm ezinn-client || true
            docker run -d --name ezinn-client -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/ezinn-client:latest
