name: Build on Pull Request

env:
  ENV: .env

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: .env
    if: github.event.pull_request.head.ref != 'main' && github.event.pull_request.head.ref != 'develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Inject environment variables
        run: echo "${{ secrets.ENV }}" > .env

      - name: Install dependencies
        run: npm install --force

      - name: Build application
        run: npm run build
